# Generated by Django 5.2.6 on 2025-09-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('phone_number', models.CharField(help_text='Enter your phone number', max_length=10, verbose_name='Phone Number')),
                ('instagram_id', models.CharField(blank=True, null=True, verbose_name='Instagram Id')),
                ('whatsapp_number', models.IntegerField(blank=True, help_text='Enter your phone number without 0', null=True, verbose_name='WhatsApp Number')),
                ('telegram_id', models.URLField(blank=True, null=True, verbose_name='Telegram Id')),
            ],
            options={
                'verbose_name': 'Site Contact Info',
                'verbose_name_plural': 'Site Contact Info',
            },
        ),
    ]
