# Generated by Django 5.2.6 on 2025-09-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontactinfo',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
    ]
