# Generated by Django 5.2.6 on 2025-09-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_sitecontactinfo_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontactinfo',
            name='phone_number',
            field=models.CharField(help_text='Enter your phone number', max_length=11, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='sitecontactinfo',
            name='whatsapp_number',
            field=models.IntegerField(blank=True, help_text='Enter your phone number without 0', max_length=10, null=True, verbose_name='WhatsApp Number'),
        ),
    ]
