# Generated by Django 5.2.6 on 2025-09-26 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_sitecontactinfo_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontactinfo',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Enter your phone number without 0', max_length=10, null=True, verbose_name='WhatsApp Number'),
        ),
    ]
