# Generated by Django 5.2.6 on 2025-09-26 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_sitecontactinfo_whatsapp_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontactinfo',
            name='telegram_id',
            field=models.CharField(blank=True, null=True, verbose_name='Telegram Id'),
        ),
    ]
