# Generated by Django 5.2.6 on 2025-09-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_sitecontactinfo_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontactinfo',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='sitecontactinfo',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Enter your phone number', max_length=11, null=True, verbose_name='Phone Number'),
        ),
    ]
