# Generated by Django 5.2.6 on 2025-09-11 09:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='address',
            field=models.TextField(default='', verbose_name='address'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='', max_length=100, verbose_name='city'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(default='', help_text='Enter your lastname.', max_length=100, verbose_name='Lastname'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='', help_text='Enter your name.', max_length=100, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='postal_code',
            field=models.CharField(default='', max_length=10, verbose_name='postal_code'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='province',
            field=models.CharField(default='', max_length=100, verbose_name='province'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text='09 ', max_length=11, unique=True, validators=[django.core.validators.RegexValidator(regex='^09\\d{9}$')], verbose_name='Phone Number'),
        ),
    ]
