# Generated by Django 5.2.6 on 2025-09-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_username_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='lastname',
            field=models.CharField(default='', max_length=100, verbose_name='Lastname'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Name'),
        ),
    ]
