# Generated by Django 5.2.6 on 2025-09-13 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_lastname_alter_customuser_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='province',
            field=models.CharField(default='', max_length=10, verbose_name='province'),
        ),
    ]
