# Generated by Django 5.2.6 on 2025-09-10 12:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('author', models.CharField(max_length=50, verbose_name='Author')),
                ('source', models.CharField(max_length=100, verbose_name='Source')),
                ('source_link', models.URLField(blank=True, null=True)),
                ('text', ckeditor.fields.RichTextField()),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('datetime_modified', models.DateTimeField(auto_now=True, verbose_name='date edited')),
                ('image', models.ImageField(upload_to='blog/blog_cover/', verbose_name='blog Image')),
                ('status', models.CharField(choices=[('pub', 'published'), ('drf', 'draft')], max_length=3, verbose_name='Status')),
            ],
        ),
    ]
