# Generated by Django 5.2.6 on 2025-09-26 12:39

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_coupon_options_coupon_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='datetime_created',
            field=django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='datetime_expired',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True, verbose_name='Expired At'),
        ),
    ]
