# Generated by Django 5.2.6 on 2025-09-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_shipping_coupon_used_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipping',
            name='cost_on_delivery',
            field=models.BooleanField(default=False, verbose_name='Cost Paid by Receiver'),
        ),
    ]
