# Generated by Django 5.2.6 on 2025-09-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_display',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Coupon Display'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_value',
            field=models.PositiveIntegerField(default=0, verbose_name='Coupon Value'),
        ),
    ]
