# Generated by Django 5.2.6 on 2025-09-14 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/', verbose_name='Image 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/', verbose_name='Image 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='products/gallery/', verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Cover Image'),
        ),
    ]
