# Generated by Django 5.2.6 on 2025-09-15 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_keyword_product_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='products', to='products.keyword', verbose_name='Keywords'),
        ),
    ]
