# Generated by Django 5.2.6 on 2025-09-26 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Coupon Code'),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='Discount Percent'),
        ),
    ]
