# Generated by Django 5.2.6 on 2025-09-26 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_coupon_code_product_discount_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='coupon_code',
        ),
        migrations.RemoveField(
            model_name='product',
            name='discount_percent',
        ),
    ]
